services:
  postgres:
    image: postgres:17-alpine
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: docker_link_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: