app:
  github-token: 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
  stackoverflow:
    key: rl_jZX15ioJuP17ww4XY5AzyDf4D
    access-token: xsFxe8fd1p3aHBGmwYx7RA))

bot:
  base-url: "http://localhost:8080"

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
