app:
  github-token: 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
  stackoverflow:
    key: rl_jZX15ioJuP17ww4XY5AzyDf4D
    access-token: xsFxe8fd1p3aHBGmwYx7RA))
  access-type: ORM

bot:
  base-url: "http://localhost:8080"

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/link_tracker
    username: postgres
    password: Stepan2005
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
